### ISSUE TITLE
Feature request: Syntax highlighting for psql files

### ISSUE THREAD

**Issue by rasputino** [JakubJanowski/PostgreSqlInAString#2]
### Issue
Currently, `.sql` files are highlighted using MSSQL syntax by default. This can sometimes lead to incorrect syntax highlighting, especially when working with PostgreSQL-specific syntax.

For example:
![Example 1](https://github.com/user-attachments/assets/b4d1d1d8-d326-4eb3-9195-b747ef691857)
![Example 2](https://github.com/user-attachments/assets/cf4a97f8-29a8-4a2c-b095-f55f0122b044)

To avoid this, I often rename my SQL files to use the `.psql` extension. However, doing so causes the syntax highlighting to be lost entirely.

### Proposed feature
It would be a great enhancement if this extension could support syntax highlighting for `.psql` files, applying PostgreSQL-specific syntax formatting. This would ensure consistent and correct highlighting when working with PostgreSQL.

**Comment by JakubJanowski** [comment]
Thanks for the suggestion. This project is focused on syntax highlighting within string literals, so I don't think that a highlighter for pure PostgreSQL files would fit here. It would be great to have it as a separate extension though; the VS marketplace is definitely lacking here.
